name: maa_yegue
description: "Ma'a yegue - Application d'apprentissage des langues traditionnelles camerounaises"
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  video_player: ^2.9.1
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.4+7
  cloud_functions: ^4.6.7
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  package_info_plus: ^8.0.0
  provider: ^6.1.1
  equatable: ^2.0.5
  go_router: ^14.0.0
  dio: ^5.4.0
  http: ^0.13.6
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dartz: ^0.10.1
  file_picker: ^8.0.0
  permission_handler: ^11.3.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_lints: ^2.0.3
  lottie: ^3.0.0
  flutter_tts: ^4.2.3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  stripe_js: ^3.2.0
  flutter_stripe: ^10.1.1
  fl_chart: ^0.66.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  bloc_test: ^9.1.4
  intl_utils: ^2.8.7
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  connectivity_plus_platform_interface: any
  sqflite_common: any
  google_sign_in_platform_interface: any
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/databases/cameroon_languages.db
    - assets/firebase/
    - assets/logo/
  generate: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.jpg"
