// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqG0_OwcU8evk2TqO2IQqFHEv3q9qwZc',
    appId: '1:853678151393:android:c448e584dca7faac9cc9a0',
    messagingSenderId: '853678151393',
    projectId: 'studio-6750997720-7c22e',
    storageBucket: 'studio-6750997720-7c22e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19nFd3V7ZXVg_gB5seZc8L9L3uLjPhZU',
    appId: '1:853678151393:ios:e5d778801dec39b19cc9a0',
    messagingSenderId: '853678151393',
    projectId: 'studio-6750997720-7c22e',
    storageBucket: 'studio-6750997720-7c22e.firebasestorage.app',
    iosBundleId: 'com.mayegue.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD19nFd3V7ZXVg_gB5seZc8L9L3uLjPhZU',
    appId: '1:853678151393:ios:e5d778801dec39b19cc9a0',
    messagingSenderId: '853678151393',
    projectId: 'studio-6750997720-7c22e',
    storageBucket: 'studio-6750997720-7c22e.firebasestorage.app',
    iosBundleId: 'com.mayegue.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4_2NdHl3zvkukTg18WRTiZC7RecMRw0',
    appId: '1:853678151393:web:40332d5cd4cedb029cc9a0',
    messagingSenderId: '853678151393',
    projectId: 'studio-6750997720-7c22e',
    storageBucket: 'studio-6750997720-7c22e.firebasestorage.app',
    authDomain: 'studio-6750997720-7c22e.firebaseapp.com',
    measurementId: 'G-F60NV25RDJ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe4_2NdHl3zvkukTg18WRTiZC7RecMRw0',
    appId: '1:853678151393:web:40332d5cd4cedb029cc9a0',
    messagingSenderId: '853678151393',
    projectId: 'studio-6750997720-7c22e',
    storageBucket: 'studio-6750997720-7c22e.firebasestorage.app',
    authDomain: 'studio-6750997720-7c22e.firebaseapp.com',
  );
}
