// Mocks generated by Mockito 5.4.5 from annotations
// in maa_yegue/test/features/authentication/domain/usecases/register_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:maa_yegue/features/authentication/domain/entities/auth_response_entity.dart'
    as _i2;
import 'package:maa_yegue/features/authentication/domain/entities/user_entity.dart'
    as _i3;
import 'package:maa_yegue/features/authentication/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponseEntity_0 extends _i1.SmartFake
    implements _i2.AuthResponseEntity {
  _FakeAuthResponseEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i3.UserEntity?>.empty(),
      ) as _i5.Stream<_i3.UserEntity?>);

  @override
  _i5.Future<_i2.AuthResponseEntity> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<_i2.AuthResponseEntity> signUpWithEmailAndPassword(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailAndPassword,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #signUpWithEmailAndPassword,
            [
              email,
              password,
              displayName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<_i2.AuthResponseEntity> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<_i2.AuthResponseEntity> signInWithFacebook() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithFacebook,
          [],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #signInWithFacebook,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<_i2.AuthResponseEntity> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #signInWithApple,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<_i2.AuthResponseEntity> signInWithPhoneNumber(
          String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhoneNumber,
          [phoneNumber],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #signInWithPhoneNumber,
            [phoneNumber],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<_i2.AuthResponseEntity> verifyPhoneNumber(
    String? verificationId,
    String? smsCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneNumber,
          [
            verificationId,
            smsCode,
          ],
        ),
        returnValue:
            _i5.Future<_i2.AuthResponseEntity>.value(_FakeAuthResponseEntity_0(
          this,
          Invocation.method(
            #verifyPhoneNumber,
            [
              verificationId,
              smsCode,
            ],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponseEntity>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserEntity?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.UserEntity?>.value(),
      ) as _i5.Future<_i3.UserEntity?>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.UserEntity> updateUserProfile(_i3.UserEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [user],
        ),
        returnValue: _i5.Future<_i3.UserEntity>.value(_FakeUserEntity_1(
          this,
          Invocation.method(
            #updateUserProfile,
            [user],
          ),
        )),
      ) as _i5.Future<_i3.UserEntity>);

  @override
  _i5.Future<void> deleteUserAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserAccount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
